network/chats/urls.py
from django.urls import path
from chats.views import private_chat_view, chat_main_view

app_name = 'chats'

urlpatterns = [
    path('', chat_main_view, name='main'),
    path('<int:user_id>/', private_chat_view, name='private-chat'),
]

network/network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('chats/', include('chats.urls', namespace='chats')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

network/posts/urls.py
from django.urls import path
from posts.views import (
    post_comment_create_and_list_view,
    react_post,
    PostDeleteView,
    PostUpdateView,
    create_report_view,
    admin_view,
)


app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_and_list_view, name='post-main'),
    path('reacted/', react_post, name='react-post'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:post_id>/report', create_report_view, name='make_report'),
    path('admin/', admin_view, name='admin-view')
]

network/profiles/urls.py
from django.urls import path
from profiles.views import (
    profile_view,
    invites_received_view,
    ProfileListView,
    invite_profiles_list_view,
    send_invitation,
    remove_from_friends,
    accept_invite,
    reject_invite,
    ProfileDetailView,
    SearchByPhotoView,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile', profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invite, name='accept-invite'),
    path('my-invites/reject/', reject_invite, name='reject-invite'),
    path('search-by-photo/', SearchByPhotoView.as_view(), name='search-by-photo'),
]

network/templates/main/home.html
{% extends 'base.html' %}

{% block title %}
home
{% endblock title %}

{% block content %}
{{hello}}
<br>
{{user}}
{% endblock content %}

{% block scripts %}
<script>
$(document).ready(function(){
    console.log('working')
})
</script>
{% endblock scripts %}

network/templates/main/navbar.html
{% url 'home-view' as path_to_home %}
{% url 'posts:post-main' as path_to_posts %}
{% url 'profiles:my-profile-view' as path_to_my_profile %}
{% url 'profiles:my-invites-view' as path_to_my_invites %}
{% url 'profiles:invite-profiles-view' as path_to_invites %}
{% url 'profiles:all-profiles-view' as path_to_all_profiles %}
{% url 'chats:main' as path_to_chat %}
{% url 'posts:admin-view' as path_to_admin %}

<div class="ui inverted menu nav mb-9">
  <div class="ui container">
    <a href="{{path_to_home}}" class="{% if request.path == path_to_home %}active{% endif %} item">
        <h3>Find by face</h3>
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{path_to_posts}}" class="{% if request.path == path_to_posts %}active{% endif %} item">
        Posts
    </a>

    {% if request.user.profile.admin %}
    <a href="{{ path_to_admin }}" class="{% if request.path == path_to_admin %}active{% endif %} item">
        Admin
    </a>
    {% endif %}

    <a href="{{path_to_chat}}" class="{% if request.path == path_to_chat %}active{% endif %} item">
        Chat
    </a>
    {% endif %}

    <div class="right menu">
        {% if request.user.is_authenticated %}
        <div class="item">
            <div class="ui floating dropdown icon button teal"> Friends
                <i class="dropdown icon"></i>
                <div class="menu">
                    <a href="{{path_to_all_profiles}}" class="{% if request.path == path_to_all_profiles %}active{% endif %} item">
                        All Profiles
                    </a>
                    <a href="{{path_to_invites}}" class="{% if request.path == path_to_invites %}active{% endif %} item">
                        Send Invites
                    </a>
                    <a href="{{path_to_my_invites}}" class="{% if request.path == path_to_my_invites %}active{% endif %} item">
                        Received Invites &nbsp; <div class="ui purple horizontal label">{{invites_num}}</div>
                    </a>
                </div>
             </div>
        </div>

          <a href="{% url 'profiles:search-by-photo' %}" class="ui primary button">
            Найти профили по фотографии
          </a>

            <a href="{{path_to_my_profile}}" class="{% if request.path == path_to_my_profile %}active{% endif %} item">
                <img src={{picture.url}} class="ui_avatar_image">&nbsp;
                 {{ request.user }}
            </a>

            <a href="{% url 'account_logout' %}" class="ui item">
                Logout
            </a>
        {% else %}
        <a href="{% url 'account_login' %}" class="ui item">
                Login
            </a>
        {% endif %}
    </div>
  </div>
</div>