network/chats/urls.py
from django.urls import path
from chats.views import private_chat_view, chat_main_view

app_name = 'chats'

urlpatterns = [
    path('', chat_main_view, name='main'),
    path('<int:user_id>/', private_chat_view, name='private-chat'),
]

network/network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('chats/', include('chats.urls', namespace='chats')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

network/profiles/urls.py
from django.urls import path
from profiles.views import (
    profile_view,
    invites_received_view,
    ProfileListView,
    invite_profiles_list_view,
    send_invitation,
    remove_from_friends,
    accept_invite,
    reject_invite,
    ProfileDetailView,
    SearchByPhotoView,
)

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile', profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('to-invite/', invite_profiles_list_view, name='invite-profiles-view'),
    path('send-invite/', send_invitation, name='send-invite'),
    path('remove-friend/', remove_from_friends, name='remove-friend'),
    path('<slug>', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('my-invites/accept/', accept_invite, name='accept-invite'),
    path('my-invites/reject/', reject_invite, name='reject-invite'),
    path('search-by-photo/', SearchByPhotoView.as_view(), name='search-by-photo'),
]

network/chats/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from profiles.models import Profile
from .utils import generate_chat_room_name


@login_required
def chat_main_view(request):
    profile = Profile.objects.get(user=request.user)
    friends = profile.get_friends_profiles()

    return render(request, 'chats/main.html', {'friends': friends})


@login_required
def private_chat_view(request, user_id):
    room_name = generate_chat_room_name(request.user.id, user_id)
    return render(request, 'chats/chatroom.html', {'room_name': room_name})

network/chats/templates/chats/chat_message.html
<div class="chat-message {% if message.author == request.user %}chat-message-sent{% else %}chat-message-received{% endif %}">
    <div class="chat-message-content">
        <strong><a href="{{ message.author.profile.get_absolute_url }}">{{ message.author.username }}</a></strong>: {{ message.body }}
        <span class="chat-message-time">{{ message.timestamp }}</span>
    </div>
</div>

network/chats/templates/chats/chatroom.html
{% extends 'base.html' %}

{% block title %}Chat Room{% endblock title %}

{% block content %}
<div class="container">
    <div class="chat-header">
        <h1>Chat with User {{ user_id }}</h1>
    </div>
    <div class="chat-messages" id="chat-messages">
        <!-- Здесь будут отображаться сообщения чата -->
    </div>
    <div class="chat-input">
        <input type="text" id="message-input" placeholder="Type your message...">
        <button id="send-button">Send</button>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>
    const roomName = "{{ room_name }}";
    const chatSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/chats/' + roomName + '/'
    );
    const currentUser = "{{ user.id }}";

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const chatMessages = document.querySelector('#chat-messages');
        const messageElement = document.createElement('div');

        messageElement.className = data.sender == currentUser ? 'chat-message chat-message-sent' : 'chat-message chat-message-received';

        messageElement.innerHTML = `
            <div class="chat-message-content">${data.message}</div>
            <div class="chat-message-time">${new Date(data.timestamp).toLocaleTimeString()}</div>
        `;
        chatMessages.appendChild(messageElement);
        chatMessages.scrollTop = chatMessages.scrollHeight;
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.getElementById('send-button').onclick = function() {
        const messageInputDom = document.getElementById('message-input');
        const message = messageInputDom.value;
        const sender = currentUser;

        if (message.trim()) {
            const timestamp = new Date().toISOString();
            chatSocket.send(JSON.stringify({
                'message': message,
                'timestamp': timestamp,
                'sender': sender
            }));
            messageInputDom.value = '';
        }
    };

    document.getElementById('message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // Enter key
            document.getElementById('send-button').click();
        }
    };
</script>
{% endblock scripts %}

{% block extra_styles %}
<style>
    .chat-message {
        padding: 5px;
        margin-bottom: 10px;
        border-radius: 5px;
    }

    .chat-message-sent {
        text-align: right;
        background-color: #dcf8c6;
    }

    .chat-message-received {
        text-align: left;
        background-color: #f1f0f0;
    }

    .chat-message-content {
        display: inline-block;
    }

    .chat-message-time {
        font-size: 0.8em;
        color: #999;
    }

    .container {
        display: flex;
        flex-direction: column;
        height: 100vh;
    }

    .chat-messages {
        flex: 1;
        overflow-y: auto;
        padding: 10px;
        border: 1px solid #ddd;
        margin-bottom: 10px;
    }

    .chat-input {
        display: flex;
    }

    .chat-input input {
        flex: 1;
        padding: 10px;
        border: 1px solid #ddd;
        border-right: none;
    }

    .chat-input button {
        padding: 10px;
        border: 1px solid #ddd;
        background-color: #4CAF50;
        color: white;
        cursor: pointer;
    }
</style>
{% endblock extra_styles %}

network/chats/templates/chats/main.html
{% extends 'base.html' %}



{% block title %}
Chats
{% endblock title %}

{% block content %}
    {% if friends|length == 0 %}
        <h1>You have no friends to chat with</h1>
    {% endif %}

    {% for obj in friends %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="row">
                    <div class="three wide column">
                        <img class="ui small circular image" src={{obj.avatar.url}}>
                    </div>
                    <div class="thirteen wide column">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                         <a href={{obj.get_absolute_url}}><button class="ui primary button mb-5 w-big">See profile</button></a>
                        <br>
                        <a href={% url 'chats:private-chat' user_id=obj.user.id %}><button class="ui primary button mb-5 w-big">Chat</button></a>
                        <br>

                        <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Remove from friends</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}